{% set version = "0.7.0" %}

package:
  name: physt
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - packaging
    - python
    - setuptools
    - pip
  run:
    - packaging
    - python >=3.7
    - numpy >=1.20
    - typing_extensions

test:
  # Python imports
  imports:
    - physt
    - physt.compat
    - physt.io
    - physt.helpers
    - physt.plotting

about:
  home: https://github.com/janpipek/physt
  license: MIT License
  summary: 'P(i/y)thon h(i/y)stograms.'
