name: Physt

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        include:
          - os: windows-latest
            python: "3.13"

          - os: macos-latest
            python: "3.13"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.24"
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pytest
        run: uv run pytest

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.24"
          python-version: 3.12
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run mypy (on source)
        run: uv run mypy src/physt

      - name: Run mypy (on tests)
        run: uv run mypy tests

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.24"
          python-version: 3.12
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build
        run: uv build
